#!/bin/bash
set -e

# This script starts the database server.
echo "Creating user root for databases loaded from w3af_test.sql"

echo "Adding data into MySQL"
/usr/sbin/mysqld & sleep 5

mysql --default-character-set=utf8 < /var/www/webroot/moth/setup/w3af_test.sql
mysqladmin shutdown
echo "Finished"

# Now the provided user credentials are added
/usr/sbin/mysqld & sleep 5
echo "Creating user"
echo "CREATE USER 'root' IDENTIFIED BY 'moth'" | mysql --default-character-set=utf8
echo "REVOKE ALL PRIVILEGES ON *.* FROM 'root'@'%'; FLUSH PRIVILEGES" | mysql --default-character-set=utf8
echo "GRANT SELECT ON *.* TO 'root'@'%'; FLUSH PRIVILEGES" | mysql --default-character-set=utf8
echo "finished"

# And we restart the server to go operational
mysqladmin shutdown

# SSH configuration
echo "root:MxqQt6iKUP6igE" | chpasswd
echo "ubuntu:MxqQt6iKUP6igE" | chpasswd

exec supervisord -n
